name: Build & Deploy Jekyll Site

on:
  push:
    branches: [main]

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Install dependencies
        run: |
          cd docs
          gem install bundler
          bundle install

      - name: Build Jekyll site
        run: JEKYLL_ENV=production bundle exec jekyll build --source docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_site
          publish_branch: gh-pages