name: Build & Deploy Jekyll Site
on: { push: { branches: [ main ] } }

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - run: bundle lock --add-platform x86_64-linux

      - name: Build Jekyll site
        env: { JEKYLL_ENV: production }
        run: bundle exec jekyll build -d _site

      - name: Upload _site artifact
        uses: actions/upload-artifact@v4       # 手动上传
        with:
          name: github-pages
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - id: deploy
        uses: actions/deploy-pages@v2          # 官方 Pages 部署
